require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContractorReviewsController do

  # This should return the minimal set of attributes required to create a valid
  # ContractorReview. As you add validations to ContractorReview, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "contractor_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContractorReviewsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all contractor_reviews as @contractor_reviews" do
      contractor_review = ContractorReview.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contractor_reviews).should eq([contractor_review])
    end
  end

  describe "GET show" do
    it "assigns the requested contractor_review as @contractor_review" do
      contractor_review = ContractorReview.create! valid_attributes
      get :show, {:id => contractor_review.to_param}, valid_session
      assigns(:contractor_review).should eq(contractor_review)
    end
  end

  describe "GET new" do
    it "assigns a new contractor_review as @contractor_review" do
      get :new, {}, valid_session
      assigns(:contractor_review).should be_a_new(ContractorReview)
    end
  end

  describe "GET edit" do
    it "assigns the requested contractor_review as @contractor_review" do
      contractor_review = ContractorReview.create! valid_attributes
      get :edit, {:id => contractor_review.to_param}, valid_session
      assigns(:contractor_review).should eq(contractor_review)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ContractorReview" do
        expect {
          post :create, {:contractor_review => valid_attributes}, valid_session
        }.to change(ContractorReview, :count).by(1)
      end

      it "assigns a newly created contractor_review as @contractor_review" do
        post :create, {:contractor_review => valid_attributes}, valid_session
        assigns(:contractor_review).should be_a(ContractorReview)
        assigns(:contractor_review).should be_persisted
      end

      it "redirects to the created contractor_review" do
        post :create, {:contractor_review => valid_attributes}, valid_session
        response.should redirect_to(ContractorReview.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contractor_review as @contractor_review" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContractorReview.any_instance.stub(:save).and_return(false)
        post :create, {:contractor_review => { "contractor_id" => "invalid value" }}, valid_session
        assigns(:contractor_review).should be_a_new(ContractorReview)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ContractorReview.any_instance.stub(:save).and_return(false)
        post :create, {:contractor_review => { "contractor_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contractor_review" do
        contractor_review = ContractorReview.create! valid_attributes
        # Assuming there are no other contractor_reviews in the database, this
        # specifies that the ContractorReview created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ContractorReview.any_instance.should_receive(:update_attributes).with({ "contractor_id" => "1" })
        put :update, {:id => contractor_review.to_param, :contractor_review => { "contractor_id" => "1" }}, valid_session
      end

      it "assigns the requested contractor_review as @contractor_review" do
        contractor_review = ContractorReview.create! valid_attributes
        put :update, {:id => contractor_review.to_param, :contractor_review => valid_attributes}, valid_session
        assigns(:contractor_review).should eq(contractor_review)
      end

      it "redirects to the contractor_review" do
        contractor_review = ContractorReview.create! valid_attributes
        put :update, {:id => contractor_review.to_param, :contractor_review => valid_attributes}, valid_session
        response.should redirect_to(contractor_review)
      end
    end

    describe "with invalid params" do
      it "assigns the contractor_review as @contractor_review" do
        contractor_review = ContractorReview.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContractorReview.any_instance.stub(:save).and_return(false)
        put :update, {:id => contractor_review.to_param, :contractor_review => { "contractor_id" => "invalid value" }}, valid_session
        assigns(:contractor_review).should eq(contractor_review)
      end

      it "re-renders the 'edit' template" do
        contractor_review = ContractorReview.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ContractorReview.any_instance.stub(:save).and_return(false)
        put :update, {:id => contractor_review.to_param, :contractor_review => { "contractor_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contractor_review" do
      contractor_review = ContractorReview.create! valid_attributes
      expect {
        delete :destroy, {:id => contractor_review.to_param}, valid_session
      }.to change(ContractorReview, :count).by(-1)
    end

    it "redirects to the contractor_reviews list" do
      contractor_review = ContractorReview.create! valid_attributes
      delete :destroy, {:id => contractor_review.to_param}, valid_session
      response.should redirect_to(contractor_reviews_url)
    end
  end

end
